version: '3'

# Serviços a serem colocados em containeres
services:

  # Database é um container a ser criado
  bancodados:
    image: 'postgres:0.1'
    ports:
      #      port foward, redirecionamento de porta
      #      porta da máquina : porta do container
      - 15432:5432
    environment:
      #      variaveis de ambiente do container
      - POSTGRES_PASSWORD=minhaSenha
      - POSTGRES_USERNAME=meuUsuario
    networks:
      #      Rede que o container fará parte
      - postgres-network
    volumes:
      #      Local de armazenamento de dados
      #      Enviar dados externos para o armazenamento interno do container
      - ${PWD}/db-data/:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15433:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=marcos@email.com
      - PGADMIN_DEFAULT_PASSWORD=aaa
    depends_on:
      # esse serviço depende de outro, usa o nome de referencia
      - bancodados
    networks:
      - postgres-network
    volumes:
      - ${PWD}/pgadmin-data/:/var/lib/pgadmin/

networks:
  postgres-network:
    driver: bridge